# Generated by Django 4.2.8 on 2023-12-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('id_right_answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.TextField()),
                ('answers', models.ManyToManyField(related_name='answers', to='posts.answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quesion', to='posts.questions')),
                ('test_in_cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cource')),
            ],
        ),
    ]
