# Generated by Django 4.2.8 on 2023-12-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='id_right_answer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
