# Generated by Django 4.2.8 on 2024-02-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_in_cource',
            new_name='test_in_course',
        ),
    ]
