# Generated by Django 4.2.8 on 2024-06-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('multiple', 'Multiple')], default='multiple', max_length=8),
        ),
    ]
