# Generated by Django 4.2.8 on 2024-01-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_answer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image',
        ),
    ]
