# Generated by Django 4.2.8 on 2024-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_question_qtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='lead_time',
            field=models.CharField(default=90, max_length=120),
            preserve_default=False,
        ),
    ]
