# Generated by Django 4.2.8 on 2023-12-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='slug',
            field=models.SlugField(default='med', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
